### ISSUE TITLE
stub out landing page for https://mirai.audio

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#1]
# Goal / Issue

Setup repo and stub out landing page

## Tasks

* [x] Finalize [DNS registration](https://gandi.net)
* [x] Provision [Cloudflare](https://cloudflare.com) for forwarding
* [x] Create GitHub repo for landing page
  * [x] Implement a basic landing page
  * [x] Create a MailChimp signup form

**Comment by 0xadada** [comment]
Signup form completed, closes #5
