### ISSUE TITLE
implement colophon

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#10]
# Goal

Design & Write a colophon describing our style, acting as a living design styleguide.

## Considerations

* Typeface layout: http://morisawa-resources.s3.amazonaws.com/uploads/ung/font_family/set_sample_file/60/Kanteiryu.pdf
* Typography layout: https://typekit.com/fonts/tbnpmincho-std/details/tbnpmincho-std-l
* Component library

**Web Font**

[Available online at Linotype](https://www.linotype.com/1176904/yu-kantei-family.html)

```css
@font-face {
  font-family: "Yu Kantei OTF W00 U";
  src: url("//fast.fonts.net/dv2/2/2a3f5506-db41-4ebb-a95a-a0738f83c365.eot?d44f19a684109620e484147ea690e818ee8d0f94c8efc5f31894b30255d761b9baed50f9f7bf286f78cb7d22838d1d51d956d04b899f396349fc66afa3141d12bd86108ae07dbc");
  src: url("//fast.fonts.net/dv2/2/2a3f5506-db41-4ebb-a95a-a0738f83c365.eot?d44f19a684109620e484147ea690e818ee8d0f94c8efc5f31894b30255d761b9baed50f9f7bf286f78cb7d22838d1d51d956d04b899f396349fc66afa3141d12bd86108ae07dbc#iefix")
    format("embedded-opentype"),
  url("//fast.fonts.net/dv2/14/d52289a6-3129-4544-ac68-d80908f8a7c3.woff2?d44f19a684109620e484147ea690e818ee8d0f94c8efc5f31894b30255d761b9baed50f9f7bf286f78cb7d22838d1d51d956d04b899f396349fc66afa3141d12bd86108ae07dbc")
    format("woff2"),
  url("//fast.fonts.net/dv2/3/eb7d7d8e-ec0d-4cb7-9582-eec3c5782f73.woff?d44f19a684109620e484147ea690e818ee8d0f94c8efc5f31894b30255d761b9baed50f9f7bf286f78cb7d22838d1d51d956d04b899f396349fc66afa3141d12bd86108ae07dbc")
    format("woff"),
  url("//fast.fonts.net/dv2/1/2d76e1fc-a965-4e37-9c32-221158521053.ttf?d44f19a684109620e484147ea690e818ee8d0f94c8efc5f31894b30255d761b9baed50f9f7bf286f78cb7d22838d1d51d956d04b899f396349fc66afa3141d12bd86108ae07dbc")
    format("truetype");
}
```

Load woff2 first. Do not use system or local fonts.

```css
/* Lato Light
 * latin
 */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 300;
  src: url('/fonts/lato/lato-light-latin.woff2') format('woff2'),
       url('/fonts/lato/lato-light-latin.woff') format('woff');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}
```

## Tasks

* [x] Buy typeface from provider
  * Implement web-loading css `@font-face` rules
* [x] Implement a layout
* [x] Create all typographic variants
* [x] Implement all typographic colors
* [x] Implement all typographic sizes
* [x] Implement all typographic weights
* [x] Include buttons, widgets, layouts
* [ ] Table of contents to follow [HTML element Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
