### ISSUE TITLE
implement css linting

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#13]
# Goal / Issue

CSS changes will be processed by a CSS linter to prevent syntax errors and bad practices prior to deployment.

## Considerations

Read https://css-tricks.com/stylelint/

* [stylelint](https://github.com/stylelint/stylelint)

## Tasks

* [ ] Configure stylelint manually on the CLI
* [ ] Add rules to match our code conventions
* [ ] Add linter to the build process
* [ ] Add broccoli-clean-css to build process

**Comment by 0xadada** [comment]
Moved tasks into #7
