### ISSUE TITLE
implement javascript linting

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#15]
# Goal

Enforce syntax and style rules for javascript.

> Code linting is a type of static analysis that is frequently used to find problematic patterns or code that doesn’t adhere to certain style guidelines. There are code linters for most programming languages, and compilers sometimes incorporate linting into the compilation process.
>
> JavaScript, being a dynamic and loosely-typed language, is especially prone to developer error. Without the benefit of a compilation process, JavaScript code is typically executed in order to find syntax or other errors. Linting tools like ESLint allow developers to discover problems with their JavaScript code without executing it.

## Considerations

* [ESLint](eslint.org/docs/rules/)
* [StandardJS](http://standardjs.com/)
* [pokedex.org .eslintrc](https://github.com/nolanlawson/pokedex.org/blob/master/.eslintrc)

## Tasks

List all of the subtasks that will contribute to completion of this issue. Once
all subtasks are complete, that will indicate the issue is "done".

* [x] Add ESLint to project
* [x] Configure rules to match the styleguide
  * [x] Update styleguide if any new changes
