### ISSUE TITLE
[mir] user can manually add media to library

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#16]
# Goal

User can add a media item to their library manually.

## Tasks

**Mir**

* [x] Implement`media` model & tests
* [x] Implement `media` form & tests
  * [x] Add new action
  * [ ] Edit action
  * [x] Delete action
* [x] Implement `media` form validation, load state, success state & failure states
* [x] Implement `media` acceptance tests
  * [x] media add acceptance tests
  * [ ] media edit acceptance tests
  * [x] media delete acceptance tests
* [x] Update circle ci docker image to `circleci/node:carbon-browsers`

## Testing

**Create**

1. User logs in successfully.
1. User clicks the "Add" button. The new media form appears.
1. User enters the URL, title and clicks "Add". New media form disappears, showing success.
1. User sees that the new media item was added to their library.

**Edit**

1. User logs in successfully.
1. User clicks the "Edit" button. The edit media form appears.
1. User edits the title & URL and clicks "Save". New media form disappears, showing success.
1. User sees that the media item has changed.

**Delete**

1. User logs in successfully.
1. User clicks the "Delete" button a media item. A confirmation dialog appears.
1. User clicks "yes". The confirmation dialog disappears, and the media item disappears.
1. User sees that the media item was removed.

## Considerations

github feature branch: `16/library`.

**Comment by 0xadada** [comment]
Upgrade ember to 2.18

**Comment by 0xadada** [comment]
This ticket will include https://github.com/mirai-audio/mir/issues/36
