### ISSUE TITLE
Implement images as svg sprites

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#17]
# Goal / Issue

Use SVG icon sprites

## Considerations

Read [Icon system with svg sprites](https://css-tricks.com/svg-sprites-use-better-icon-fonts/)
on css-tricks.com then read [svg symbols](https://css-tricks.com/svg-symbol-good-choice-icons/)

## Tasks

List all of the subtasks that will contribute to completion of this issue. Once
all subtasks are complete, that will indicate the issue is "done".

* [x] Read svg sprites
* [ ] Read [svg symbols](https://css-tricks.com/svg-symbol-good-choice-icons/)
* [ ] Test/try [svg symbol sprite codepen](https://codepen.io/0xADADA/pen/MJdabZ)
* [x] `svg-jar`
* [ ] Try [npm svgstore](https://www.npmjs.com/package/svgstore)
  * [ ] [gulp-svgstore](https://www.npmjs.com/package/gulp-svgstore)
