### ISSUE TITLE
Create contributing / conduct guidelines

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#2]
# Goal / Issue

Create contributing / conduct guidelines page.

## Considerations

Contributing.md

* [Node collaboration](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md)
* [ember.js](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md)
* [brave](https://github.com/brave/browser-laptop/blob/master/.github/CONTRIBUTING.md)
* [homebrew contributing](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)

CONDUCT.md

* [homebrew conduct](https://github.com/caskroom/homebrew-cask/blob/master/CONDUCT.md)
* [ToDo MVC code of conduct](https://github.com/tastejs/todomvc/blob/master/code-of-conduct.md)
* [Node CODE_OF_CONDUCT.md](https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md)
* [Rust conduct](https://www.rust-lang.org/en-US/conduct.html)

## Tasks

* [x] Create an issue on GitHub
* [x] Read codes & contributions elsewhere
* [x] Write CONDUCT.md
* [x] Write CONTRIBUTING.md

**Comment by 0xadada** [comment]
* [Code of Conduct](https://github.com/mirai-audio/mir/wiki/CODE_OF_CONDUCT)
* [Contributing](https://github.com/mirai-audio/mir/wiki/CONTRIBUTING)

Closes #2
