### ISSUE TITLE
improve testing baselines

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#21]
# Goal

Set quality testing baselines.

## Tasks

* [x] `/index` tests
  * [x] Unauthorized users land on the `/welcome` page when `/`
  * [x] Unauthorized users cannot visit the `/typography` or `/styleguide` pages.
  * [x] Authorized users can visit the `/` page
* [x] `/login` tests
  * [x] Unauthorized users can visit the `/login` page
  * [x] Unauthorized users can create a new email account and be logged in
  * [x] Unauthorized users cannot create a new email account without confirming their password
  * [x] Unauthorized users can login with their new email account 
  * [ ] Unauthorized users can login with twitter
  * [x] Unauthorized users cannot login with an invalid email
  * [x] Unauthorized users cannot login with an invalid password
* [x] `/logout` tests
  * [x] Unauthorized users can logout by visiting the `/logout` route
  * [x] Logout unauthorizes the user and redirects them to the welcome page
* [x] `/styleguide` tests
  * [x] Authorized users can visit the `/styleguide` and `/typography` pages
* [x] `ember-cli-mirage`
* [ ] https://emberobserver.com/addons/ember-cli-code-coverage

**Comment by 0xadada** [comment]
Free browserstack Firefox testing https://www.browserstack.com/test-on-firefox-browser
