### ISSUE TITLE
Implement initial deploy

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#22]
# Goal

Use `[ember-cli-deploy](https://github.com/tomdale/ember-cli-deploy-elastic-beanstalk)` to deploy Ember fastboot as a docker container onto Amazon Elastic Beanstalk or Digital Ocean.

## Considerations

Where will it be hosted? AWS, Google, Digital Ocean, Docker Cloud?

## Tasks

* [ ] Write Dockerfile for project
* [ ] Install `ember-cli-deploy` and deploy plugins
  * [ ] Configure them
* [ ] Create hosting provider account
* Get the deploy working
* Try a release
