### ISSUE TITLE
design basic route structure

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#25]
# Goal

Design a clean URL structure.

## Considerations

Twitter and GitHub provide good examples

## Tasks

List all of the subtasks that will contribute to completion of this issue. Once
all subtasks are complete, that will indicate the issue is "done".

* [ ] Design URL structure
* [] `https://mirai.audio` `/` main app (dashboard or stream)
  * [ ] `/:user` user/artist profile
    * [ ] `/:user/library` users library
    * [ ] `/:user/lists` users playlists
  * [ ] `/lists/:list` playlist
  * [ ] `/media/:media` media info page
