### ISSUE TITLE
implement ember-cli-one-script

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#26]
# Goal

## Tasks

* [ ] test page speed
* [ ] install `ember-cli-one-script`
* [ ] test page speed
  * [ ] Merge if its got a noticeable page speed improvement
