### ISSUE TITLE
user can sign up

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#28]
# Goal

User can sign up

### Expected Behavior

User visits site, user is logged out. User see welcome page.

User user Twitter to login. User is logged in and sees their feed.

User closes browser. User reopens browser and comes back to the site. User is still logged in.

User Closes browser. User returns 90 days later. User is still logged in. Returns 91 days later. User is logged out.

## Considerations

Read about Phoenix / Elixir

* [x] [PEEP](https://resolve.digital/blog/posts/creating-a-todo-application-using-the-phoenix-framework-and-ember-js/)
* [x] [Peek stack 2](https://medium.com/@j_mcnally/the-peep-stack-b7ba5afdd055)
* [x] [Peep stack](https://github.com/colindensem/peep-stack)
* [ ] [Peek stack series](https://medium.com/peep-stack)
* [ ] Read [account design mistakes](https://articles.uie.com/account_design_mistakes/)

## Tasks

* [x] Setup ai repo
* [ ] ember-simple-auth
  * [x] Torii
  * [x] Configure email registration
  * [x] Configure email login
  * [x] Implement twitter registration
    * [x] https://github.com/0xadada/ember-oauth-workshop
  * [x] Implement twitter login
* [x] Create hello-world app
* [x] Setup postgres dockerfile for app
