### ISSUE TITLE
Bootstrap basic ember app

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#3]
# Goal

Bootstrap basic ember app

## Considerations

* [Ember.js .editorconfig](https://github.com/emberjs/ember.js/blob/master/.editorconfig)
* [Advisor .editorconfig](https://github.com/cinch-financial/advisor/blob/develop/.editorconfig)
* [Ember.js ESLintrc](https://github.com/emberjs/ember.js/blob/master/.eslintrc.js)
* [Keybase](https://github.com/keybase/client/blob/master/.editorconfig)

Ember packages

* ember-cli-sass
* ember-cli-fastboot
* [ember-cli-eslint](https://emberobserver.com/addons/ember-cli-eslint)
* ember-i18n
* ember-cli-deploy
* ember-freestyle
* ember-cli-inline-content
* broccoli-serviceworker

Investigate

* Svelte

## Tasks

* [x] Specify `.editorconfig` settings
* [x] Run ember generator
* [x] Get a basic "hello world" app running
* [x] ember-cli-sass
* [x] Cleanout unused bootstrap default code
* [x] ember-cli-fastboot
* [x] [ember-cli-eslint](https://emberobserver.com/addons/ember-cli-eslint)
* [x] Specify JSHint / ESLint -JSCS- settings
  * [x] Implement `eslint-config-airbnb`
* [x] ember-i18n
* [x] Use `yarn` over npm
  * [x] Add `yarn` to dependencies/prereqs
  * [x] Update docs to reference `yarn` over `npm`
* [x] Deprecate [bower](https://bower.io) per the [Ember.js 2.11 release
   docs](http://emberjs.com/blog/2017/01/23/ember-2-11-released.html#toc_ember-no-longer-supplied-via-code-bower-code)
  * [x] Update README to remove refs to Bower
  * [x] Update `circle.yml` to remove refs to bower

**Comment by 0xadada** [comment]
https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Testing

**Comment by 0xadada** [comment]
Add `VERSION` to router

```javascript
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: config.rootURL,
  version: config.APP.version,
});
```
