### ISSUE TITLE
Create a styleguide

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#4]
# Goal / Issue

Create a styleguide, add to the **wiki** not docroot

## Considerations

* [ember styleguide](https://github.com/emberjs/ember.js/blob/master/STYLEGUIDE.md)
* [brave styleguide](https://github.com/brave/browser-laptop/blob/master/docs/style.md)

## Tasks

List all of the subtasks that will contribute to completion of this issue. Once all subtasks are complete, that will indicate the issue is "done".

* [x] Create a styleguide for CSS
* [x] Create a styleguide for HTML
* [x] Create a styleguide for Javascript
