### ISSUE TITLE
Setup contact endpoints

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#5]
# Goal / Issue

Allow users, collaborators and others to contact the project and its maintainers.

## Tasks

* [x] Find a free mail hosting provider
  * [x] Setup mailbox for new email for myself
  * [x] Setup general mailbox for team
    * [x] Setup as default mailbox & setup forwarding
    * [x] Setup auto-responder
  * [x] Setup mail forwarding to project owners
  * [x] Configure DNS `mx` records on Cloudflare to point to mail provider
* [x] Create twitter account
  * [x] Enable 2FA

**Comment by 0xadada** [comment]
Chose mail hosting provider Yandex

* Support for custom domains
* Free
* Supports default / catch-all mailboxes
* Supports IMAP

**Comment by 0xadada** [comment]
[@MiraiAudio](https://twitter.com/miraiaudio)

Closes #5

**Comment by 0xadada** [comment]
Closes: #5
