### ISSUE TITLE
configure Ember app build targets

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#57]
_Configure [Ember build targets](https://guides.emberjs.com/v2.16.0/configuring-ember/build-targets/) such that the build is slim and optimized for the proper set of browsers to support._

In {{configure/targets.js}}, Ember will use Babel to transpile code for browsers listed in the targets array.

h2. Supported list

browserl.ist/?q=>+1.5%25+in+US
`> 1.5% in US` 

## Tasks

* [ ] Determine optimal set of browsers to support
* [ ] Update [testem.js](https://github.com/mirai-audio/mir/blob/master/testem.js) to test supported browsers
* [ ] Update [Browser-Support](https://github.com/mirai-audio/mir/wiki/Browser-Support)

`Testem.js`
```javascript
module.exports = {
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  launch_in_ci: [
    'Chrome'
  ],
  launch_in_dev: [
    'Chrome',
    'Chrome Canary',
    'Firefox',
    'Safari'
  ],
  'browser_args': {
    'Chrome': chromeArgs,
    'Chrome Canary': chromeArgs,
    'Firefox': [
      '-headless', /* headless available on v55+ on Linux, 56+ on Windows/Mac */
      '--window-size=1024,768'
    ]
  }
};
```
