### ISSUE TITLE
[ai] Endpoint to support media

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#58]
# Goal

Ai provides an endpoint for Mir to create new media items.

## Tasks

**Ai**

* [ ] Implement`media` model & tests
* [x] Implement `media` insert
* [ ] Implement `media` update
* [x] Implement `media` delete
* [x] REST endpoints
* [ ] channel endpoints

## Considerations

github feature branch: `58/library`.
