### ISSUE TITLE
design logo

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#6]
# Goal / Issue

Define a core brand. Logo

## Considerations

Usage of a [Japanese Mon (紋)](https://en.wikipedia.org/wiki/Mon_(emblem)) as a logo (preferably one with a corresponding emoji, or combination of two). Some area available [at crest-japan.net](http://eps.crest-japan.net/index_en.php) or [secure.ne.jp](https://x181.secure.ne.jp/~x181007/kamon/goodslist.cgi)

### Logo

Another idea is the reappropriation of an existing _mon_:

[![Ogasawara mon](https://upload.wikimedia.org/wikipedia/commons/d/d4/Mon_ogasawara.svg)](http://crest-japan.net/htdocs/epsImages/marunisankaibishi.eps)
<small>Example: The Ogasawara mon</small>

One idea is to utilize the play icon (▶️) in a circle, or arranged as a triforce, encircled.

> it was considered improper to use a mon that was known to be held by someone else, and
> offensive to use a mon that was held by someone of a high rank. When mon came into
> conflict, the lower-ranked person sometimes changed their mon to avoid offending their
> superior<sup>[[1](https://en.wikipedia.org/wiki/Mon_(emblem)#History)]</sup>.
> ...
> There are no set rules in the design of a mon. Most consist of a roundel encircling a figure of plant, animal, man-made, natural or celestial objects, all abstracted to various degrees. Religious symbols, geometric shapes and kanji were commonly used as well.
> ...
> Similar to the blazon in European heraldry, mon are also named by the content of the design, even though there is no set rule for such names. Unlike in European heraldry, however, this "blazon" is not prescriptive—**the depiction of a mon does not follow the name—instead the names only serve to describe the mon**.

_["Maruni Hitotsu Uroko" (Inside circle, single [fish] scale)](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:%E4%B8%B8%E3%81%AB%E4%B8%80%E3%81%A4%E9%B1%97.jpg)_

## Tasks

* [x] Create github repo
* [x] Design a basic logo, in svg
  * [x] Design a typographic logo, a logotype
  * [x] Generate other formats from svg: PNG/gif/jpg for:
    * [x] `favicon.ico`
    * [x] `apple-touch-icon.png`
    * [x] GitHub organization avatar
    * [x] gravatar
* [x] Add to homepage

## Refs

* [Mon](https://en.wikipedia.org/wiki/Mon_(emblem)#History)
* [Cadency](https://en.wikipedia.org/wiki/Cadency)
* [TozandoShop](tozandoshop.com/v/vspfiles/kamon/geometry2.html)

**Comment by 0xadada** [comment]
Text linting for natural language https://github.com/textlint/textlint/blob/master/README.md

**Comment by 0xadada** [comment]
Final design!
![mirai-audio-512x512](https://cloud.githubusercontent.com/assets/51207/22859278/42ea3b9c-f0a4-11e6-9366-88362f523b57.jpg)
