### ISSUE TITLE
investigate static analysis for css

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#7]
# Goal / Issue

Parker is a simple static analysis tool that gives you some very insightful metrics about your CSS files. Parker surfaces some really interesting numbers, and if you know what they represent, you can draw some really valuable insights and improve css performance with them.

## Considerations

* [Improving your css with parker](https://csswizardry.com/2016/06/improving-your-css-with-parker/)

## Considerations

* [stylelint](https://github.com/stylelint/stylelint)
  * [ember-cli-stylelint](https://github.com/billybonks/ember-cli-stylelint)
  * [configuration](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md)
* [stylelint-config-wikimedia](https://github.com/wikimedia/stylelint-config-wikimedia)
* [18F stylelint-config](https://github.com/18F/stylelint-rules/blob/master/src/stylelint-config.js)

## Tasks

List all of the subtasks that will contribute to completion of this issue. Once
all subtasks are complete, that will indicate the issue is "done".

* [x] Read https://css-tricks.com/stylelint/
* [x] Add rules to match our code conventions
* [x] Configure stylelint manually on the CLI
* [x] Add linter to the build process
* [x] Add [autoprefixer](https://github.com/postcss/autoprefixer)
* [x] Read https://code.facebook.com/posts/879890885467584/improving-css-quality-at-facebook-and-beyond/
* [x] Read about parker
* [x] ~Add parker to project~ seems deprecated vs PostCSS
  * [ ] Write worst-case tests to show failure states
  * [ ] Create a ruleset to result in failure for specific anti-patterns
  * [ ] Too many uses of !important
  * [ ] Too many selectors
  * [ ] Selectors nested too deeply
* [x] ember-cli-inline-content
