### ISSUE TITLE
investigate PWAs progressive web apps

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#9]
# Goal

What features of Progressive Web Apps can we prioritize? What examples can we use for inspiration?

### Talks

https://www.youtube.com/watch?v=cmGr0RszHc8&index=2&list=WL

### Examples

* [Flipkart](https://www.flipkart.com/)
* [Pokedex.org](https://github.com/nolanlawson/pokedex.org#readme)
* [A ton more](https://pwa.rocks/)

### Service Workers

```javascript
/* on page */
if (navigator.serviceWorker) {
  navigator.serviceWorker.register("/sw.js");
}
/* sw.js */
console.log("Hello world");
```

## Tasks

* [x] [Read](https://www.smashingmagazine.com/2016/08/a-beginners-guide-to-progressive-web-apps/)
* [x] Add: meta-name-theme-color
* [x] Add: link-rel-manifest
```javascript
// manifest.json
{
  "name": "mirai.audio",
  "start_url": "/app",                   /* URL app starts when added to home */
  "background_color": "#ffffff", /* spash bg */
  "theme_color": "#000000",     /* status bar */
  "icons": [{},{}],
  "...": "...",
}
```

* [x] https://developers.google.com/web/progressive-web-apps/
* [x] https://developers.google.com/web/fundamentals/getting-started/primers/service-workers?hl=en
* [x] https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers
* [x] https://webmasters.googleblog.com/2016/11/building-indexable-progressive-web-apps.html
* [x] https://developers.google.com/web/fundamentals/performance/prpl-pattern/
* [x] Implement "Add to Home" feature appearing in Chrome-mobile
  * [Docs](https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/#what_are_the_criteria)
* [x] Implement basic MVP offline capability
* [x] [Remove old caches that aren't in the current cache](https://jakearchibald.com/2014/offline-cookbook/#on-activate)

**Comment by 0xadada** [comment]
Checkout this example service worker, a google doodle

```javascript
var EXTRA_FILES = [
  "/xjs/_/js/k=xjs.ntp.en_US.jbDpzVZQrgw.O/m=jsa,ntp,d,csi/am=Gg/rt=j/d=1/t=zcms/rs=ACT90oF05ga3aevv1AhnIZ97NR90Rjti3Q",
];
var CHECKSUM = "iehank";

var BLACKLIST = [
  '/gen_204\?',
  '/async/',
];

var FILES = [
  '/images/srpr/logo11w.png',
  '/images/srpr/chrome_ntp_white_logo2.png',
      '/' + '/ssl.gstatic.com/chrome/components/doodle-notifier-01.html'
].concat(EXTRA_FILES || []);

var CACHENAME = 'newtab-static-' + CHECKSUM;

self.addEventListener('install', function(event) {
  event.waitUntil(caches.open(CACHENAME).then(function(cache) {
    return cache.addAll(FILES);
  }));
});

self.addEventListener('activate', function(event) {
    return event.waitUntil(caches.keys().then(function(keys) {
    return Promise.all(keys.map(function(k) {
      if (k != CACHENAME && k.indexOf('newtab-static-') == 0) {
        return caches.delete(k);
      } else {
        return Promise.resolve();
      }
    }));
  }));
});

self.addEventListener('fetch', function(event) {
  event.respondWith(
      caches.match(event.request).then(function(response) {
        if (response) {
                    return response;
        }

        return fetch(event.request).then(function(response) {
          var shouldCache = true;

          for (var i = 0; i < BLACKLIST.length; ++i) {
            var b = new RegExp(BLACKLIST[i]);
            if (b.test(event.request.url)) {
              shouldCache = false;
              break;
            }
          }

          if (event.request.method == 'POST') {
            shouldCache = false;
          }

                    if (shouldCache) {
            return caches.open(CACHENAME).then(function(cache) {
              cache.put(event.request, response.clone());
              return response;
            });
          } else {
            return response;
          }
        });
      })
  );
});



if (!Cache.prototype.add) {
  
  Cache.prototype.add = function add(request) {
        return this.addAll([request]);
  };
}

if (!Cache.prototype.addAll) {
  
  Cache.prototype.addAll = function addAll(requests) {
        var cache = this;

        function NetworkError(message) {
      this.name = 'NetworkError';
      this.code = 19;
      this.message = message;
    }
    NetworkError.prototype = Object.create(Error.prototype);

    return Promise.resolve().then(function() {
      if (arguments.length < 1) throw new TypeError();

            var sequence = [];

      requests = requests.map(function(request) {
        if (request instanceof Request) {
          return request;
        }
        else {
          return String(request);          }
      });

      return Promise.all(
          requests.map(function(request) {
            if (typeof request === 'string') {
              request = new Request(request);
            }

            return fetch(request.clone());
          })
      );
    }).then(function(responses) {
                  return Promise.all(
          responses.map(function(response, i) {
            return cache.put(requests[i], response);
          })
      );
    }).then(function() {
      return undefined;
    });
  };
}

if (!CacheStorage.prototype.match) {
    
  CacheStorage.prototype.match = function match(request, opts) {
    var caches = this;
    return caches.keys().then(function(cacheNames) {
      var match;
      return cacheNames.reduce(function(chain, cacheName) {
        return chain.then(function() {
          return match || caches.open(cacheName).then(function(cache) {
            return cache.match(request, opts);
          }).then(function(response) {
            match = response;
            return match;
          });
        });
      }, Promise.resolve());
    });
  };
}
```

**Comment by 0xadada** [comment]
```javascript
self.addEventListener('activate', function(e) {
  console.log('[ServiceWorker] Activate');
  e.waitUntil(
    caches.keys().then(function(keyList) {
      return Promise.all(keyList.map(function(key) {
        if (key !== cacheName) {
          console.log('[ServiceWorker] Removing old cache', key);
          return caches.delete(key);
        }
      }));
    })
  );
  return self.clients.claim();
});
```
