### ISSUE TITLE
migrate to ember-intl

### ISSUE THREAD

**Issue by 0xadada** [mirai-audio/mir#97]
[Ember Intl](https://github.com/ember-intl/ember-intl) has better feature support and supports the ICU message syntax & Native Intl API.

## Tasks

* [x] install ember-intl
* [x] refactor using the [codemod](https://github.com/DockYard/ember-i18n-to-intl-migrator)
* [x] refactor ember-i18n-changeset-validations to [ember-intl-changeset-validations](https://gitlab.com/michal.bryxi/ember-intl-changeset-validations)
* [x] refactor `app/instance-initializers/i18n.js` to support ember-intl
* [x] uninstall ember-i18n
